//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstalledSoftware
    {
        public int id { get; set; }
        public Nullable<int> Инвентарный_Номер_ПК { get; set; }
        public Nullable<int> Продукт { get; set; }
        public Nullable<System.DateTime> Дата_Установки { get; set; }
    
        public virtual PC PC { get; set; }
        public virtual Software Software { get; set; }
    }
}
