//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prktEntities : DbContext
    {
        public prktEntities()
            : base("name=prktEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PC> PC { get; set; }
        public virtual DbSet<Software> Software { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ТИП_ПО> ТИП_ПО { get; set; }
        public virtual DbSet<ТИП_РАСПРОСТРАНЕНИЯ> ТИП_РАСПРОСТРАНЕНИЯ { get; set; }
        public virtual DbSet<ТИП_УСТРОЙСТВА> ТИП_УСТРОЙСТВА { get; set; }
        public virtual DbSet<InstalledSoftware> InstalledSoftware { get; set; }
    }
}
