//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Software()
        {
            this.InstalledSoftware = new HashSet<InstalledSoftware>();
        }
    
        public int id { get; set; }
        public string Наименование_Продукта { get; set; }
        public Nullable<int> Тип_ПО { get; set; }
        public Nullable<int> Тип_распространения { get; set; }
        public Nullable<int> Количество_Лицензий { get; set; }
        public Nullable<int> Остаток_Лицензий { get; set; }
    
        public virtual ТИП_ПО ТИП_ПО1 { get; set; }
        public virtual ТИП_РАСПРОСТРАНЕНИЯ ТИП_РАСПРОСТРАНЕНИЯ1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstalledSoftware> InstalledSoftware { get; set; }
    }
}
